### PR TITLE
Add setup for Gowin FPGAs - Tang Nano 9K dev board

### PR DESCRIPTION
**Pull request by IvanVeloz**
Hi everyone,

This is a PR to add a setup for Gowin FPGAs, specifically supporting the Tang Nano 9K development board. It's a $20 board with 8,640 LUTs, 468kbit of BSRAM,  64Mbit integrated SDRAM, 32Mbit SPI flash and HDMI output. I am not affiliated with the manufacturer, but I think this board is an excellent platform to experiment with soft processors and it has just enough hardware to boot Linux.

This setup was developed and tested on the Gowin EDA version 1.9.9. It builds successfully, presents the bootloader and is able to run the `blink_led` example. It uses the build-in programmer as its USB-UART interface (read the readme for usage). In the future, another setup supporting the external SPI flash can be implemented.

Best regards,
Ivan Veloz

### CODE REVIEW

**Comment by stnolting** [comment]
Hey @IvanVeloz, thank you very much for your contribution! Finally, we have a complete new FPGA family here 🎉

Just two things from my side:

* Please add a final line break to all (source) files. Yes, it is not crucial and just a matter of taste, but then we can avoid those tiny warning signs rendered by GitHub 😉

grafik

* Please add a link to your port to the front page's README: https://github.com/stnolting/neorv32-setups/blob/main/README.md#setups-using-commercial-toolchains

Thanks again for your great work! :)

**Comment by IvanVeloz** [comment]
Hi Stephan,

Sounds good, I will do these changes this weekend.

Best,
Ivan

**Comment by IvanVeloz** [comment]
Hi Stephan,

I made the modifications you requested. Sorry for the delay. It's ready for review!

Best,
Ivan

**Review by stnolting — APPROVED** [review]

**Comment by stnolting** [comment]
Thank you very much!

(the documentation you've added is really great!)

**Comment by IvanVeloz** [comment]
Thank you!

**Pull request merged**
