### PR TITLE
Add iCE40 ChipWhisperer Target board support

### PR DESCRIPTION
**Pull request by colinoflynn**
This requires the constraints PR https://github.com/hdl/constraints/pull/6 .

This is a very basic additional iCE40 board, we plan on using neorv32 as part of some demos on so would be convenient to avoid our own fork. Happy to adjust anything as needed.

### CODE REVIEW

**Comment by stnolting** [comment]
Great work! Thanks for contributing!
I suggest to wait until hdl/constraints#6 is merged so we can update that submodule before merging this.

**Comment by stnolting** [comment]
Somehow I cannot update this branch... 🤔 
Anyway, you might want to update this PR from `main` and also add your setup to the [implementation workflow](https://github.com/stnolting/neorv32-setups/blob/main/.github/generate-job-matrix.py) to have up-to-date bitstreams generated on every repository update by GitHub actions.

**Comment by colinoflynn** [comment]
Got it - so switch the PR to come from my "main" branch you mean right? I'll close this one & re-open a new one to avoid weird git issues if so (along with adding the integration).

**Comment by umarcor** [comment]
@colinoflynn I believe he meant rebasing your ice40cw312-support branch on top of the main branch of this repo. No need to close and recreate this PR, just force-push the branch.

**Comment by stnolting** [comment]
@colinoflynn 

@umarcor is right, sorry for the confusion 😅

**Comment by colinoflynn** [comment]
Got it - I misread "update", doing a rebase makes way more sense! Thanks for clarifying. I spend too long with ohshitgit.com I guess I'm too trigger-happy to just blow it away ;-)

**Comment by stnolting** [comment]
Looks good to me! :+1:
Please add your setup to the front page's readme (I can also do that after merging if you like). :wink:

Btw, it would be great if you could verify the generated bitstream on your hardware. You can find the bitstream file(s) in the assets of the setup's implementation workflow.

**Comment by colinoflynn** [comment]
I confirmed the artifact works on my HW, so seems nothing got mangled!

**Review by umarcor — APPROVED** [review]
LGTM!

**Comment by stnolting** [comment]
Is there any "official" documentation yet for the board? Or even a place to purchase it?
Then we could add a link to the [overview](https://github.com/stnolting/neorv32-setups#setups-using-open-source-toolchains) in the front page's readme.

**Comment by umarcor** [comment]
@stnolting you could use a ref to https://hdl.github.io/constraints/Data/Boards/index.html#ice40cw312, so when the doc refs are updated there, users can find all of them without updating the info here.

**Comment by colinoflynn** [comment]
Oops missed the github ping this AM! The "most stable" link is the github design docs (https://github.com/newaetech/chipwhisperer-target-cw308t/tree/main/CW312T_ICE40UP) it gets rendered to another site (rtfm.newae.com) but those URLs may change if things get rearranged. It's not available yet as a "real" product so it's still just the design files.

The constraints file is already pointing there, so that seems like a safe method too (and maybe shows the value of the constraints file).

**Comment by stnolting** [comment]
Great, I will add that link.

**Pull request merged**
