### PR TITLE
move content from subdir 'setups' of neorv32 to repo neorv32-setups

### PR DESCRIPTION
**Pull request by umarcor**
As the title suggest, this PR brings all the content of subdir `setups` from NEORV32. NEORV32 is added as a submodule. Furthermore, the following content is moved too:

- Dockerfiles and CI workflow `Containers`.
- CI workflow `Implementation`, including GNU/Linux and Windows jobs.
  `generate-job-matrix.py`, which is used in the workflow `Implementation`.
  
I'm unsure about the default token having permissions to push containers from this repo. That should work. I think it's failing at the moment because I was the one pushing the branch. However, if pushed by @stnolting (or after merging) it should work.

### CODE REVIEW

**Review by stnolting — APPROVED** [review]

**Comment by stnolting** [comment]
Awesome! Thank you very much!

**Comment by stnolting** [comment]
Where do we want to have the containers? Shouldn't this be also changed to `neorv32-setups`? 🤔 

https://github.com/stnolting/neorv32-setups/blob/d36953850fad36fada39da0e6694180a5240ce74/.github/workflows/Containers.yml#L29

**Comment by umarcor** [comment]
It seems that the default token in this repo does not have permissions to push to `ghcr.io/stnolting/neorv32/`. We have three options:

- Push to `ghcr.io/stnolting/neorv32-setups/` and update the image names here and in NEORV32.
- Use a token (add it as a secret) with enough permissions to push to `ghcr.io/stnolting/neorv32/` from here.
- Move the Containers workflow back to NEORV32.

**Comment by stnolting** [comment]
> Push to ghcr.io/stnolting/neorv32-setups/ and update the image names here and in NEORV32.

I think this is the most straightforward approach. What do you think?

**Comment by umarcor** [comment]
> I think this is the most straightforward approach. What do you think?

I'm unsure because the containers are `impl` and `sim`, and the latter is not used in this repo. Hence, I think it makes more sense for image names to be `neorv32` only.

**Comment by stnolting** [comment]
Good point!

> to be neorv32 only.

:+1:

**Pull request merged**
