### PR TITLE
[CI/Containers] use a secret token, instead of the default

### PR DESCRIPTION
**Pull request by umarcor**
I will keep this as a draft because I cannot edit the secrets of the repo myself.

### CODE REVIEW

**Comment by stnolting** [comment]
I am little confused about this tokens... 😅 
Does the `GITHUB_TOKEN` does not have sufficient rights?

**Comment by umarcor** [comment]
> I am little confused about this tokens... 😅 Does the `GITHUB_TOKEN` do not have sufficient rights?

The default GITHUB_TOKEN (`github.token`) has right to push to neorv32-setups, but not to neorv32. See https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/ and https://docs.github.com/en/actions/security-guides/automatic-token-authentication#granting-additional-permissions. So, we need a PAT of yours with `read:packages` and `write:packages` permissions. No other permissions should be required.

**Comment by umarcor** [comment]
Note that I don't need to know the PAT. You just create it and add it as a secret in this repo. Then let me know the name of the secret (not the content).

**Comment by stnolting** [comment]
Ah ok, I think I finally understand 😅 
I have created a PAT with the according rights and added it to this repository. Token name `PACKAGE_TOKEN`.

**Pull request merged**
