### PR TITLE
Revert 159 main

### PR DESCRIPTION
**Pull request by lovelesh-mis**
- Reverted changes to synthesis.mk
- Added iCEBreaker on-board LEDs to the top module

### CODE REVIEW

**Comment by stnolting** [comment]
Thanks for the update!

**Review by stnolting — APPROVED** [review]

**Review by umarcor — COMMENTED** [review]
It seems that some other changes were unwantedly added to this PR. Particularly an empty binary file is added. Pease, remove at least that one.

**Comment by stnolting** [comment]
I think the changes in the Radiant version are fine.

So in my opinion it's ready to be merged :+1:

**Review by stnolting — APPROVED** [review]

**Comment by lovelesh-mis** [comment]
Yes.

Regards,
Lovelesh Patel
Firmware Engineer
MIS Electronics

**Pull request merged**
